
NGINX_VERSION = "1.9.12"
NGINX_SRC = "#{ENV['HOME']}/build/nginx-#{NGINX_VERSION}"
NGINX_HOME = "#{ENV['HOME']}/opt/nginx"
MODULE_HOME = "/home/vagrant/g/dojo/cc/ngx/print"
MODULE_NAME = "ngx_http_print_module"

task :default => :test

task :build  do
  Dir.chdir(NGINX_SRC) do
    sh "./configure --prefix=#{NGINX_HOME} --add-module=#{MODULE_HOME}"
  end
end

task :install  do
  Dir.chdir(NGINX_SRC) do
    sh "make install"
  end
end

task :start  do
  sh "#{NGINX_HOME}/sbin/nginx"
end

task :stop  do
  sh "#{NGINX_HOME}/sbin/nginx -s stop"
end

task :reload  do
  sh "#{NGINX_HOME}/sbin/nginx -s reload"
end

task "edit-config"  do
  sh "vim #{NGINX_HOME}/conf/nginx.conf"
end


task :test  do
  sh "curl http://localhost:8080/print"
end

task :a do
  Dir.chdir(NGINX_SRC) do
    sh "cc -c -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -o objs/addon/print/#{MODULE_NAME}.o /home/vagrant/g/dojo/cc/ngx/print/#{MODULE_NAME}.c"
  end
end

