
NGINX_SRC="#{ENV['HOME']}/build/nginx-1.9.12"
NGINX_HOME="#{ENV['HOME']}/opt/nginx"
MODULE_HOME="/home/vagrant/g/dojo/cc/ngx/foo"

task :default => :test

task :build  do
	Dir.chdir(NGINX_SRC) do
		sh "./configure --prefix=#{NGINX_HOME} --add-module=#{MODULE_HOME}"
		sh "make && make install"
	end
end

task :start  do
	sh "#{NGINX_HOME}/sbin/nginx"
end

task :stop  do
	sh "#{NGINX_HOME}/sbin/nginx -s stop"
end

task :reload  do
	sh "#{NGINX_HOME}/sbin/nginx -s reload"
end

task :test  do
	sh "curl http://localhost:8080/foo"
end

task :a do
	Dir.chdir(NGINX_SRC) do
	  sh "cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -o objs/addon/foo/ngx_http_foo_module.o /home/vagrant/g/dojo/cc/ngx/foo/ngx_http_foo_module.c"
	end
end

