task :default => :main

task :mruby do
  puts 'hello'

  Dir.chdir('mruby') do
    sh "pwd"

    # ./mruby/examples/mrbgems/c_extension_example
  end

  #git clone https://github.com/mruby/mruby.git
  #cd mruby
  #rake
end

