/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Foo */

#ifndef _Included_Foo
#define _Included_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Foo
 * Method:    say
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Foo_say
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
