/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Foo */

#ifndef _Included_Foo
#define _Included_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Foo
 * Method:    sendInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Foo_sendInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     Foo
 * Method:    sendString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Foo_sendString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Foo
 * Method:    sendStrings
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Foo_sendStrings
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
