/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Foo */

#ifndef _Included_Foo
#define _Included_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Foo
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Foo_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
